// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzyNT69BBdEXWASVx23d-_Bit292rkS-0',
    appId: '1:286382661329:web:b79f711153474bcdbe6ff0',
    messagingSenderId: '286382661329',
    projectId: 'easy-order-app-900b1',
    authDomain: 'easy-order-app-900b1.firebaseapp.com',
    storageBucket: 'easy-order-app-900b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOSqUTMjZzU-LM1OmexuYVw2XcsLo9SbU',
    appId: '1:286382661329:android:5b0b39c8b6a04714be6ff0',
    messagingSenderId: '286382661329',
    projectId: 'easy-order-app-900b1',
    storageBucket: 'easy-order-app-900b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATSSbXELDX6V6RExRiBXorBpvWsH0ECZ4',
    appId: '1:286382661329:ios:7c168ded5b9a15cdbe6ff0',
    messagingSenderId: '286382661329',
    projectId: 'easy-order-app-900b1',
    storageBucket: 'easy-order-app-900b1.firebasestorage.app',
    iosBundleId: 'com.manap.easyorder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATSSbXELDX6V6RExRiBXorBpvWsH0ECZ4',
    appId: '1:286382661329:ios:7c168ded5b9a15cdbe6ff0',
    messagingSenderId: '286382661329',
    projectId: 'easy-order-app-900b1',
    storageBucket: 'easy-order-app-900b1.firebasestorage.app',
    iosBundleId: 'com.manap.easyorder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzyNT69BBdEXWASVx23d-_Bit292rkS-0',
    appId: '1:286382661329:web:39dc5811bed5d8e4be6ff0',
    messagingSenderId: '286382661329',
    projectId: 'easy-order-app-900b1',
    authDomain: 'easy-order-app-900b1.firebaseapp.com',
    storageBucket: 'easy-order-app-900b1.firebasestorage.app',
  );
}
